### ISSUE TITLE
how to train this network to recognize new gestures?

### ISSUE THREAD

**Issue by Vi5HaL** [jgv7/CNN-HowManyFingers#2]
I have created new data set for counting 1 to 10 fingers using this program. Now I want to train CNN for this how to do it?

**Comment by jaredvasquez** [comment]
Hi @Vi5HaL, thanks for your interest in the project! Now that you've collected your dataset you could modify the jupyter notebook code (trainModel.ipynb) to generalize to your 10 cases. This code was only intended to support 6 gestures (none+each finger) so you'll have to hack the code a little bit to fit your purposes. Good luck!
