### ISSUE TITLE
Origin of Dataset

### ISSUE THREAD

**Issue by pjain03** [jgv7/CNN-HowManyFingers#3]
Hey!
Where did you get this data from? And can I use it? If so,  how do I cite this?

**Comment by jaredvasquez** [comment]
Hey @pjain03, I created this dataset with a little bit of patience and the application. The application allows you to record images from video and save them to a directory labeled by a certain class. To make the dataset I just held my fingers up and started recording while rotating, moving and adjusting the gestures I was making little by little.
